### ISSUE TITLE
Shield slot not handled

### ISSUE THREAD

**Issue by duralakun** [PrismarineJS/prismarine-windows#5]
When using the clickWindow function. You can select items and place them everywhere except for
the shield slot. When trying to click the shield slot, it will work (i think) but not update the information for your bot. So you get no response, the bot thinks it dident click on the slot, wich will cause errors if you call clickWindow again. (and drop your item)

The shield slot is the last slot in the inventory. To fix this increase [link](https://github.com/PrismarineJS/prismarine-windows/blob/eece07c2697200888c14b0bd3308b31c99c63f5a/lib/windows.js#L30)
> var INVENTORY_SLOT_COUNT = 36;

by 1, to 
> var INVENTORY_SLOT_COUNT = 37;

I am again not sure if this breaks something else, so far it works fine for me. If it causes any problem i will come back and report.

**Comment by rom1504** [comment]
why did you close it ?

That seems like something to do indeed.

**Comment by duralakun** [comment]
its not as easy to fix as i thought.

Here is an [image](http://wiki.vg/images/1/13/Inventory-slots.png) that shows the different slot numbers.
Slot 45 (the last slot) is the shield slot.
But when you open a chest the shield slot disappears. So the last slot will be the last in the quick menu (slot 44 in the image)
